spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fintech}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fintech}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fintech}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT:8080}
app.jwt.secret=${APP_JWT_SECRET:fintech-secret-key-please-change-this-value-123456}

