spring.application.name=fintech
spring.datasource.url=jdbc:postgresql://localhost:5432/fintech
spring.datasource.username=fintech
spring.datasource.password=fintech
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.mvc.async.request-timeout=5000
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

